reviewers:
  default:
    - MikeWhileCoding
    - Eren073
    - Euphratesdb
    - larsvanherwijnen
    - LegeBeker
    - Mourad787
    - Neverless90
    - TimBogersGitHub

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3
  last_files_match_only: false