groups:
  - name: devs # name of the group
    reviewers: 3 # amount of reviewers
    usernames: # github usernames of the reviewers
      - MikeWhileCoding
      - Eren073
      - Euphratesdb
      - larsvanherwijnen
      - LegeBeker
      - Mourad787
      - Neverless90
      - TimBogersGitHub
